SU-300 : Implementar Nota de Débito - Producto AJUSTE
fiterlatam/web-app pull request #209
Opened 2024-10-22 06:31 UTC by tabrez-fiter

## Description
Describe the changes made and why they were made instead of how they were made. List any dependencies that are required for this change.

## Related issues and discussion
#{Issue Number}

## Screenshots, if any

## Checklist
Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] If you have multiple commits please combine them into one commit by squashing them.

- [ ] Read and understood the contribution guidelines at `web-app/.github/CONTRIBUTING.md`.

2024-10-24 13:01 UTC, faheem205 requested changes

2024-10-24 14:09 UTC, tabrez-fiter commented on src/app/loans/loans-account-stepper/loans-account-details-step/loans-account-details-step.component.html
> +            <mat-select formControlName="allyId" aria-placeholder="Oi!" (selectionChange)="changeEvent()">
i will update it soon

2024-10-25 03:27 UTC, tabrez-fiter commented
changes updated with placeholder.

2024-10-25 05:26 UTC, faheem205 approved these changes

2024-10-25 06:07 UTC, merged